### ISSUE TITLE
Debounce encoder with software

### ISSUE THREAD

**Issue by StafWars** [Jomelo/LCDMenuLib#16]
Hi, 
I would like to debounce the encoder because now I have to be really carefull with the rotary. It doesn't do what I want it to do, and i think it's because it isn't debounced. 
I would like to do the debouncing with software, because i've already made an PCB (maybe too early...)
What would your recommendations be to debounce a rotary encoder on the  LCDML_CONTROL page.
I've worked with delays, but that didn't do much...

Kind regard!

StafWars

**Comment by Jomelo** [comment]
The encoder is doubonced over the backend system. The time on "LCDML_BACKEND_control" is to large.

Test following:
LCDML_BACK_new_timebased_dynamic (0  , ( 10UL )         , _LCDML_start  , LCDML_BACKEND_control);

or 

LCDML_BACK_new_timebased_dynamic (0  , ( 5UL )         , _LCDML_start  , LCDML_BACKEND_control);

I will rewrite this part on weekend. At the moment i cannot find my encoder :-(

**Comment by StafWars** [comment]
Thanks for the fast respons. 
But when I try this, it doesn't compile. Or do I  have to insert it on a library file?

Kind regards

StafWars


![image](https://cloud.githubusercontent.com/assets/17925272/15566733/d799fa20-2322-11e6-82d4-7e30fd62c0f9.png)
