### ISSUE TITLE
Use Joystick control

### ISSUE THREAD

**Issue by dreep** [Jomelo/LCDMenuLib#19]
// *********************************************************************
// *************** (5) CONTROL OVER JOYSTICK *********************
// *********************************************************************
#elif(_LCDML_CONTROL_cfg == 5)
// settings
  #define _LCDML_CONTROL_analog_pinx              A0
  #define _LCDML_CONTROL_analog_piny              A1
  #define _LCDML_CONTROL_digitalread              33 //don't work with u8glib

  // when you did not use a button set the value to zero
//  #define _LCDML_CONTROL_analog_enter_min        612     // Button Enter
//  #define _LCDML_CONTROL_analog_enter_max        1023  
  #define _LCDML_CONTROL_analog_up_min           612     // Button Up
  #define _LCDML_CONTROL_analog_up_max           1023   
  #define _LCDML_CONTROL_analog_down_min         0     // Button Down
  #define _LCDML_CONTROL_analog_down_max         412   
//  #define _LCDML_CONTROL_analog_back_min         0     // Button Back
//  #define _LCDML_CONTROL_analog_back_max         412   
  #define _LCDML_CONTROL_analog_left_min         612    // Button Left
  #define _LCDML_CONTROL_analog_left_max         1023 
  #define _LCDML_CONTROL_analog_right_min        0    // Button Right
  #define _LCDML_CONTROL_analog_right_max        412
// *********************************************************************
// setup
void LCDML_CONTROL_setup()
{
//  Serial.begin(9600);
  pinMode (_LCDML_CONTROL_digitalread, INPUT);
}
// *********************************************************************
// loop
void LCDML_CONTROL_loop()
{
  // check debounce timer  
  if((millis() - g_LCDML_DISP_press_time) >= _LCDML_DISP_cfg_button_press_time) {
    g_LCDML_DISP_press_time = millis(); // reset debounce timer
    
    uint16_t valuex = analogRead(_LCDML_CONTROL_analog_pinx);  // analogpinx
    uint16_t valuey = analogRead(_LCDML_CONTROL_analog_piny);  // analogpinx
    uint16_t valuee = digitalRead (_LCDML_CONTROL_digitalread);  //digitalpinenter
    
//    if (valuee == HIGH) { LCDML_BUTTON_enter(); } //HIGH with pull up resistor
    if (valuey >= _LCDML_CONTROL_analog_up_min    && valuey <= _LCDML_CONTROL_analog_up_max)    { LCDML_BUTTON_up();    }
    if (valuey >= _LCDML_CONTROL_analog_down_min  && valuey <= _LCDML_CONTROL_analog_down_max)  { LCDML_BUTTON_down();  }
    if (valuex >= _LCDML_CONTROL_analog_left_min  && valuex <= _LCDML_CONTROL_analog_left_max)  { LCDML_BUTTON_quit();  } //_left
    if (valuex >= _LCDML_CONTROL_analog_right_min && valuex <= _LCDML_CONTROL_analog_right_max) { LCDML_BUTTON_enter(); } //LCDML_BUTTON_right();
//    if (valuex >= _LCDML_CONTROL_analog_back_min  && valuex <= _LCDML_CONTROL_analog_back_max)  { LCDML_BUTTON_quit();  }

  }
}
// *********************************************************************
// ******************************* END *********************************
// *********************************************************************

**Comment by Jomelo** [comment]
I add your code in version 2.2.1
