### ISSUE TITLE
error in v2.0 version

### ISSUE THREAD

**Issue by pierrotm777** [Jomelo/LCDMenuLib#3]
Hello,
I try for the first time your menu lib . I have an I2C Sainsmart 40x2 LCD screen

Your v2.0 version return error !

lcdml_i2c.ino:40:16: error: expected constructor, destructor, or type conversion before '(' token
lcdml_i2c.ino:49:15: error: expected constructor, destructor, or type conversion before '(' token
lcdml_i2c.ino:50:15: error: expected constructor, destructor, or type conversion before '(' token
lcdml_i2c.ino:51:15: error: expected constructor, destructor, or type conversion before '(' token
lcdml_i2c.ino:52:15: error: expected constructor, destructor, or type conversion before '(' token
lcdml_i2c.ino:53:15: error: expected constructor, destructor, or type conversion before '(' token
lcdml_i2c.ino:54:15: error: expected constructor, destructor, or type conversion before '(' token
lcdml_i2c.ino:55:15: error: expected constructor, destructor, or type conversion before '(' token
lcdml_i2c.ino:56:15: error: expected constructor, destructor, or type conversion before '(' token
lcdml_i2c.ino:57:15: error: expected constructor, destructor, or type conversion before '(' token
lcdml_i2c.ino:58:15: error: expected constructor, destructor, or type conversion before '(' token
lcdml_i2c.ino:59:15: error: expected constructor, destructor, or type conversion before '(' token
lcdml_i2c.ino:60:15: error: expected constructor, destructor, or type conversion before '(' token
lcdml_i2c.ino:61:15: error: expected constructor, destructor, or type conversion before '(' token
lcdml_i2c.ino:62:15: error: expected constructor, destructor, or type conversion before '(' token
lcdml_i2c.ino:63:15: error: expected constructor, destructor, or type conversion before '(' token
lcdml_i2c.ino:64:15: error: expected constructor, destructor, or type conversion before '(' token
lcdml_i2c.ino:65:15: error: expected constructor, destructor, or type conversion before '(' token
lcdml_i2c.ino:66:15: error: expected constructor, destructor, or type conversion before '(' token
lcdml_i2c.ino:67:22: error: expected constructor, destructor, or type conversion before '(' token
lcdml_i2c.ino: In function 'void setup()':
lcdml_i2c.ino:72:35: error: 'LCDMenuLib_setup' was not declared in this scope
lcdml_i2c.ino: In function 'void loop()':
lcdml_i2c.ino:81:19: error: 'LCDMenuLib_loop' was not declared in this scope
LCDML_control.ino: In function 'void LCDMenuLib_control_analog()':
LCDML_control.ino:32:6: error: 'LCDML' was not declared in this scope
LCDML_control.ino:32:18: error: 'g_LCDMenuLib_press_time' was not declared in this scope
LCDML_control.ino:37:39: error: '_LCDMenuLib_button_up' was not declared in this scope
LCDML_control.ino:40:39: error: '_LCDMenuLib_button_down' was not declared in this scope
LCDML_control.ino:43:39: error: '_LCDMenuLib_button_left' was not declared in this scope
LCDML_control.ino:46:39: error: '_LCDMenuLib_button_right' was not declared in this scope
LCDML_control.ino: In function 'void LCDMenuLib_control_digital()':
LCDML_control.ino:72:9: error: 'LCDML' was not declared in this scope
LCDML_control.ino:72:21: error: 'g_LCDMenuLib_press_time' was not declared in this scope
LCDML_control.ino:75:83: error: '_LCDMenuLib_button_up' was not declared in this scope
LCDML_control.ino:76:85: error: '_LCDMenuLib_button_down' was not declared in this scope
LCDML_control.ino:78:119: error: '_LCDMenuLib_button_left' was not declared in this scope
LCDML_control.ino:79:120: error: '_LCDMenuLib_button_right' was not declared in this scope
LCDML_control.ino: In function 'void LCDMenuLib_control_serial()':
LCDML_control.ino:89:8: error: 'LCDML' was not declared in this scope
LCDML_control.ino:89:20: error: 'g_LCDMenuLib_press_time' was not declared in this scope
LCDML_control.ino:92:51: error: '_LCDMenuLib_button_up' was not declared in this scope
LCDML_control.ino:93:51: error: '_LCDMenuLib_button_down' was not declared in this scope
LCDML_control.ino:94:51: error: '_LCDMenuLib_button_left' was not declared in this scope
LCDML_control.ino:95:51: error: '_LCDMenuLib_button_right' was not declared in this scope
LCDML_function.ino: In function 'void FUNC_init_screen()':
LCDML_function.ino:9:7: error: 'LCDML' was not declared in this scope
LCDML_function.ino:11:5: error: 'lcd' was not declared in this scope
LCDML_function.ino:27:6: error: 'LCDML' was not declared in this scope
LCDML_function.ino: In function 'void FUNC_information()':
LCDML_function.ino:37:7: error: 'LCDML' was not declared in this scope
LCDML_function.ino:40:5: error: 'lcd' was not declared in this scope
LCDML_function.ino:62:6: error: 'LCDML' was not declared in this scope
LCDML_function.ino: In function 'void FUNC_timer_info()':
LCDML_function.ino:79:7: error: 'LCDML' was not declared in this scope
LCDML_function.ino:82:5: error: 'lcd' was not declared in this scope

I use the the new LiquidCrystal_V1.2.1 version

I init my LCD like that!

#include <Wire.h>
#include <LiquidCrystal_I2C.h>
#include <LCDMenuLib.h>

/* settings for lcd */
#define _LCDMenuLib_LCD_cols             20
#define _LCDMenuLib_LCD_rows             4

/* i2c address */ 
#define _LCDMenuLib_LCD_addr             0x27

#define _LCDMenuLib_LCD_e		  2
#define _LCDMenuLib_LCD_rw		  1
#define _LCDMenuLib_LCD_rs		  0
#define _LCDMenuLib_LCD_dat4              4
#define _LCDMenuLib_LCD_dat5              5
#define _LCDMenuLib_LCD_dat6              6
#define _LCDMenuLib_LCD_dat7              7
#define _LCDMenuLib_LCD_backlight         3
#define _LCDMenuLib_LCD_backlight_pol     POSITIVE // NEGATIVE
...
Thanks for your help !

**Comment by Jomelo** [comment]
Its only a pre release.
All old examples and #defines are renamed and changed. I am still working on it. The masters code would not work with you examples.
I think that the next version is ready on (2015-03-05)
