### ISSUE TITLE
Dublicate code 

### ISSUE THREAD

**Issue by nachaliuga** [Jomelo/LCDMenuLib#31]
All values change, everything is done similar to the example 
I will leave video with a problem  I hope somebody can help :)
https://www.youtube.com/watch?v=CE-gpdlapgk

**Comment by dragoblaztr** [comment]
@nachaliuga 
Can you upload your code for give it a near looking?

**Comment by nachaliuga** [comment]
http://forum.arduino.cc/index.php?topic=476638.0
there are alot stupid stuff over there  if you need full code let me know :)

**Comment by Jomelo** [comment]
Thanks, i will have a look on it, when i am at home on sunday. At the moment i have no access to any PC. (Only Handy)

**Comment by dragoblaztr** [comment]
@nachaliuga 
Can you post your main ino code? on forum you only show your disp functions

Regards

**Comment by Jomelo** [comment]
@nachaliuga 
I need your main code. I think you have a bug in the initialisation.

**Comment by nachaliuga** [comment]
https://ufile.io/8dbpy 
here it is, it was a mistake that led to value change for both but now another problem is that cursor doesnt want to move on the other window I realy appreciate your help

**Comment by Jomelo** [comment]
What happens, when you change your control method to serial ? 
What mean you with "other window", which window ?

**Comment by nachaliuga** [comment]
I'm idiot forget it case is closed  :D
