### ISSUE TITLE
Wire issue with the v2 beta1 version

### ISSUE THREAD

**Issue by pierrotm777** [Jomelo/LCDMenuLib#4]
Wen i compile your example (not I2C LCD 'LCDML_type_lcd4bit.ino' ) i need to add <#include Wire.h> .

Why ?

**Comment by Jomelo** [comment]
Did you use the orginal LiquidCrystal Lib  or an extern ?

**Comment by pierrotm777** [comment]
I use the New LiquidCrystal V1.3.0 ...

**Comment by Jomelo** [comment]
I think, that this lib needs the wire lib. I test my lib without wire.h and it works.

**Comment by pierrotm777** [comment]
What lib do you use ?

**Comment by Jomelo** [comment]
Its fixed, you can now use every lib u want.
