### ISSUE TITLE
Issue with library name

### ISSUE THREAD

**Issue by cmaglie** [Jomelo/LCDMenuLib#46]
Hi @Jomelo    

we have detected a discrepancy in the library name written inside `library.properties`
  `LCDMenuLib`
and the library name written inside inside the library manager index:
  `LCDMenu`

I think this is due to an error on our side when the library was registered in the library manager index (at the times this process was mostly manual).

Now we are about to introduce a change in the library manager that forbids the situation described above and the releases whose name differs from the name registered in the library index are ignored.

Is it ok for you to use the name `LCDMenuLib`? If yes, the library will be re-published with the name `LCDMenuLib` and the old `LCDMenu` will be removed from the index, in this case no action is needed on your side. In absence of an answer from you we will proceed with this proposal next week.

Thanks

See also: https://github.com/arduino/Arduino/issues/7127

```
JOB 631 - 2018/01/15 15:43:25 Checking out tag: v2.3.2
JOB 631 - 2018/01/15 15:43:25 Release LCDMenuLib:2.3.2 has wrong library name, should be LCDMenu
JOB 631 - 2018/01/15 15:43:25 Checking out tag: v2.3.3
JOB 631 - 2018/01/15 15:43:25 Release LCDMenuLib:2.3.3 has wrong library name, should be LCDMenu
JOB 631 - 2018/01/15 15:43:25 Checking out tag: v2.3.4
JOB 631 - 2018/01/15 15:43:25 Release LCDMenuLib:2.3.4 has wrong library name, should be LCDMenu
```

**Comment by Jomelo** [comment]
The name "LCDMenuLib" is ok. Please rename it.
