### ISSUE TITLE
Add info about relation to LCDMenuLib2

### ISSUE THREAD

**Issue by sixtyfive** [Jomelo/LCDMenuLib#52]
It would be helpful to those researching libraries and trying to decide on one if you could provide a short sentence in the README that says something like "for stability, use this, if you want new features use LCDMenuLib2" or similar.

**Comment by Jomelo** [comment]
Good idea, i add this to the README files

**Comment by Jomelo** [comment]
The README is updated :-)

**Comment by sixtyfive** [comment]
Nice, a complete comparison! So, if I wanted to use a cheap ST7735-based TFT that might not work with the Adafruit library (but does work with PDQ_GFX_Libs) LCDMenuLib2 would be a better starting point?

**Comment by Jomelo** [comment]
Your display can be implemented on both libs. The efford is the same. Use the new one :-)
