### ISSUE TITLE
I2C alterable address

### ISSUE THREAD

**Issue by pierrotm777** [Jomelo/LCDMenuLib#7]
Hello,
Actually, we define the I2C address with the _LCDML_DISP_addr value .
Is it possible to have an fonction that change this value ?
My goal is to read the address from the EEPROM !!!

Thanks for your job !!!

**Comment by Jomelo** [comment]
At the moment it is not possible. 
In the version v2.1 i will change the class concept to remove the settings in  ___config.h.
But at the moment i renovate my new appartment and have no time for that.

**Comment by pierrotm777** [comment]
Ok, good luck

**Comment by Jomelo** [comment]
On current master version it is possible, because i remove the ___config.h and _class.h 
The LCD Object and all LCD function can be set direct in code. 

Now you can use Graphic Displays with this Lib
